//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBanqueProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_comptes
    {
        public int IDCompte { get; set; }
        public int IDClient { get; set; }
        public string Type { get; set; }
        public long Montant { get; set; }
    
        public virtual Table_clients Table_clients { get; set; }
    }
}
