//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBanqueProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_clients()
        {
            this.Table_comptes = new HashSet<Table_comptes>();
        }
    
        public int IDClient { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public long Telephone { get; set; }
        public string Courriel { get; set; }
        public int Nip { get; set; }
        public bool Acces { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_comptes> Table_comptes { get; set; }
    }
}
