//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBanqueProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int codeTransaction { get; set; }
        public string typeTransaction { get; set; }
        public int compteFrom { get; set; }
        public Nullable<int> compteTo { get; set; }
        public System.DateTime date { get; set; }
        public decimal montant { get; set; }
    
        public virtual compte compte { get; set; }
        public virtual compte compte1 { get; set; }
    }
}
